Changed .global_driveignore location to OS config dir
shilangyu/driveignore pull request #3
Opened 2019-10-23 17:25 UTC by jketterer

Fixes #1 and adds some error catching

2019-10-23 21:45 UTC, shilangyu requested changes
After this small change ill accept the PR. Thanks for contributing!

2019-10-23 21:45 UTC, shilangyu commented on cmd/global.go
> +				vPrint(err)
vPrint is for 'verbose print' therefore the error will never be printed if verbose isnt on. Instead change the function `Run` to `RunE` and return the error.

2019-10-23 21:45 UTC, shilangyu commented on cmd/global.go
> +				vPrint(err)
same here

2019-10-25 18:33 UTC, shilangyu commented
@jketterer do you plan to make these changes?

2019-10-28 13:08 UTC, jketterer commented
@shilangyu The latest commit should fix the problem you're referring to, let me know if I missed something though.

2019-10-28 15:42 UTC, shilangyu approved these changes

2019-10-28 15:42 UTC, merged

2019-10-28 15:42 UTC, shilangyu commented
Thanks for contributing!