Add tests for global.go
shilangyu/driveignore pull request #4
Opened 2019-10-24 05:23 UTC by smoreg

* Tests
* Small refactoring to make test possible
* Small bug fixes

PR for #2

2019-10-24 08:15 UTC, shilangyu commented
This will conflict with #3, could you wait for it to be merged and rebase from there?

2019-10-28 15:46 UTC, shilangyu commented
#3 got merged, could you adjust to it?

2019-10-29 06:46 UTC, smoreg commented
@shilangyu review plz. Sorry for some refactoring.

2019-10-30 12:34 UTC, shilangyu requested changes

2019-10-30 12:34 UTC, shilangyu commented on cmd/global.go
> +		globalDriveignoreAbsPath := getAbsPathFrom(globalDriveignorePath, currDir)
this shouldnt be here, #3 added the config dir (here `globalDriveignorePath`) and we no longer care about the working directory. Please look how #3 did it.

2019-10-30 12:34 UTC, shilangyu commented on cmd/global.go
> +		globalDriveignoreAbsPath := getAbsPathFrom(globalDriveignorePath, currDir)
This seems to be the reason why tests are failing. I get the following error:
```sh
 Error:          Received unexpected error:
                                open C:\Coding\driveignore\cmd\C:\Users\Lenovo\AppData\Local\Temp\driveignore_Test_globalRun_file_n1_402933465: The filename, directory name, or volume label syntax is incorrect.
```

2019-11-05 11:33 UTC, smoreg commented on cmd/global.go
> +		globalDriveignoreAbsPath := getAbsPathFrom(globalDriveignorePath, currDir)
@shilangyu my bad,  fix pushed, check pls

2019-11-08 06:29 UTC, smoreg commented
@shilangyu

2019-11-08 09:22 UTC, shilangyu requested changes
Last change and its all good! Thanks for the help!

2019-11-08 09:22 UTC, shilangyu commented on utils/path.go
> +	return filepath.Join(dir, ".global_driveignore")
Please change to `UserConfigDir/driveignore/.global_driveignore`

2019-11-11 18:07 UTC, shilangyu commented
@smoreg

2019-11-12 05:17 UTC, smoreg commented on utils/path.go
> +	return filepath.Join(dir, ".global_driveignore")
```suggestion
	return filepath.Join(dir, "/driveignore/.global_driveignore")
```
Something like this?

2019-11-12 05:18 UTC, smoreg commented on utils/path.go
> +	return filepath.Join(dir, ".global_driveignore")
@shilangyu update with suggestion

2019-11-12 15:46 UTC, shilangyu approved these changes
awesome, thanks!

2019-11-12 15:47 UTC, merged